---
title: "Dashboard Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r instacart, include=FALSE}
data("instacart")

instacart_tidy = 
  instacart %>% 
  sample_n(100000) %>%
  mutate(order_dow = recode(order_dow, 
       "1"="Sunday",
       "2"="Monday",
       "3"="Tuesday",
       "4"="Wednesday",
       "5"="Thursday",
       "6"="Friday",
       "0"="Saturday"), 
       order_dow = factor(order_dow, 
                 levels=c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday")))

```


Column {data-width=600}
-----------------------------------------------------------------------

### Number of products ordered by department and product type (based on sample)

```{r scatterplot, message=FALSE, warning=FALSE}
instacart_tidy %>% 
  group_by(department) %>%
  count(product_name) %>%
  plot_ly(
    y = ~n, x = ~department, color = ~department, text = ~product_name,
    type = "scatter", mode = "markers")
```

Column {data-width=400}
-----------------------------------------------------------------------

### When are most fresh fruits and vegetables ordered during the week?

```{r lineplot, message=FALSE, warning=FALSE}
instacart_tidy %>% 
  filter(aisle %in% c("fresh fruits", "fresh vegetables")) %>% 
  count(order_dow) %>% 
  filter(n > 100) %>% 
  plot_ly(
    x = ~order_dow, y = ~n, color = "order_dow", 
    type = "scatter", mode = "lines", fill = "tozeroy", colors = "viridis")
```

### What are the top products people reorder?
 
```{r barplot, message=FALSE, warning=FALSE}
instacart_tidy %>% 
  filter(reordered == 1) %>% 
  count(product_name) %>% 
  mutate(product_name = fct_reorder(product_name, n)) %>% 
  filter(n > 150) %>% 
  plot_ly(
    x = ~product_name, y = ~n, color = "product_name",
    type = "bar", mode = "markers", colors = "viridis")
```


